name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Publish
      run: dotnet publish MillPlane.csproj -c Release -o release --nologo
    - name: Change base-tag in index.html for GitHub Pages
      run: sed -i 's/<base href="\/" \/>/<base href="\/mill-plane-web\/" \/>/g' release/wwwroot/index.html
    - name: Add .nojekyll file
      run: touch release/wwwroot/.nojekyll
    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4.3.0
      with:
        token: ${{ github.token }}
        branch: gh-pages
        folder: release/wwwroot
